### PR TITLE
Fix handling of Hyperlink

### PR DESCRIPTION
**Pull request by davidfischer-ch**
See: https://github.com/tomchristie/django-rest-framework/commit/90f2e26679af8741aaa1c1d0489214062c94765e.

### CODE REVIEW

**Comment by auvipy** [comment]
@jpadilla it's going to be merged ?

**Comment by jpadilla** [comment]
Sorry about that, must have missed this one. Thanks @davidfischer-ch!

**Comment by davidfischer-ch** [comment]
My pleasure!

**Comment by jpadilla** [comment]
v1.0.3 released

**Pull request merged**
